In [1]:
import numpy as np

In [2]:
#creating array from list
i=[1,23,3,4,5,2,6,3]
array=np.array(i)
array

array([ 1, 23,  3,  4,  5,  2,  6,  3])

In [3]:
#reshape of array
aa=array.reshape(4,2)
aa

array([[ 1, 23],
       [ 3,  4],
       [ 5,  2],
       [ 6,  3]])

In [4]:
#shape and type
aa.shape


(4, 2)

In [5]:
aa.dtype

dtype('int32')

#array creation: conversion from other python structure

In [6]:
listarray=np.array([[1,2,3],[4,5,6],[7,8,9]])
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
listarray.size

9

In [8]:
listarray.shape

(3, 3)

In [9]:
listarray[1,1]=8

In [10]:
listarray

array([[1, 2, 3],
       [4, 8, 6],
       [7, 8, 9]])

#intrinsic numpy array creation objects(arange,zeros,ones etc)

#identity,empty,empty_like,linspace 

In [30]:
ar1=np.arange(9,15,2)

In [31]:
ar1

array([ 9, 11, 13])

In [13]:
ar1=np.arange(20)
ar2=ar1.reshape(5,4)
ar2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [33]:
ar1=np.zeros((4,4))
ar1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
ar1=np.ones((16,4))
ar1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
ar1=np.ones((2,5))
ar1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
ar1=np.linspace(2,50,30)
ar1

array([ 2.        ,  3.65517241,  5.31034483,  6.96551724,  8.62068966,
       10.27586207, 11.93103448, 13.5862069 , 15.24137931, 16.89655172,
       18.55172414, 20.20689655, 21.86206897, 23.51724138, 25.17241379,
       26.82758621, 28.48275862, 30.13793103, 31.79310345, 33.44827586,
       35.10344828, 36.75862069, 38.4137931 , 40.06896552, 41.72413793,
       43.37931034, 45.03448276, 46.68965517, 48.34482759, 50.        ])

In [18]:
ar2=ar1.reshape(6,5)
ar2

array([[ 2.        ,  3.65517241,  5.31034483,  6.96551724,  8.62068966],
       [10.27586207, 11.93103448, 13.5862069 , 15.24137931, 16.89655172],
       [18.55172414, 20.20689655, 21.86206897, 23.51724138, 25.17241379],
       [26.82758621, 28.48275862, 30.13793103, 31.79310345, 33.44827586],
       [35.10344828, 36.75862069, 38.4137931 , 40.06896552, 41.72413793],
       [43.37931034, 45.03448276, 46.68965517, 48.34482759, 50.        ]])

In [19]:
ar1=np.identity(5)
ar1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
arr1=np.empty((4,5))
arr1

array([[4.38336741e-312, 5.92878775e-322, 0.00000000e+000,
        0.00000000e+000, 8.90110179e-308],
       [1.15998412e-028, 2.44171989e+232, 8.00801729e+159,
        6.19319847e-071, 4.57667790e-072],
       [4.57667790e-072, 6.01391519e-154, 7.06764512e-096,
        7.06743455e-096, 7.19081964e+140],
       [3.77780862e+180, 1.15998412e-028, 6.48224638e+170,
        3.67145870e+228, 1.41735275e+295]])

In [21]:
arr1=np.empty_like(ar1)
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
arr1=arr1.ravel()
arr1

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [23]:
arr1=arr1.reshape((25,1))
arr1

array([[1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.]])

In [24]:
x=[[1,2,3],[4,5,6],[7,8,9]]
ar1=np.array(x)
ar1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
ar1.sum(axis=0)

array([12, 15, 18])

In [26]:
ar1.sum(axis=1)

array([ 6, 15, 24])

In [35]:
ar1.T

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
ar1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
ar2=np.arange(9).reshape(3,3)

In [38]:
ar2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [39]:
ar2*2

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [40]:
ar2**2

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]], dtype=int32)

In [41]:
#random distribution


In [43]:
arr=np.random.rand(3,3)
arr
#Create an array of the given shape and populate it with
#random samples from a uniform distribution
#over 

array([[0.41997204, 0.55562067, 0.3091295 ],
       [0.71010935, 0.83958285, 0.07673748],
       [0.9470651 , 0.47312925, 0.38796583]])

In [47]:
arr3=np.random.randint(1,10,8)
arr3
#Return random integers from `low` (inclusive) to `high` (exclusive).

#Return random integers from the "discrete uniform" distribution of
#the specified dtype in the "half-open" interval [`low`, `high`). If
#`high` is None (the default), then results are from [0, `low`).


array([8, 4, 1, 1, 9, 9, 7, 6])